### ISSUE TITLE
Show Only Critical Issues Resets After Compiling with Auditor Open

### ISSUE THREAD

**Issue by KyleAvalani** [Unity-Technologies/ProjectAuditor#119]
**Describe the bug**
When triggering a recompile with the code auditor open in the editor, if the user has Show Only Critical Issues checked, it'll reset the content when compiling finishes. Can only be resolved by running code auditor again.

**To Reproduce**
1. Perform a project analysis with at least `Code` checked
2. Check `Show Only Critical Issues`
3. Open a script and change a line of whitespace and save
4. Switch back to Unity and wait for compiling to finish
5. Observe that all critical issues have been cleared and toggling `Show Only Critical Issues` does not bring them back.

**Expected behavior**
Compiling does not update the open audit.

**Information (please complete the following information):**
 - OS: Windows
 - Unity: 2020.3.19
 - Project Auditor version: 0.8.2

**Comment by mtrive** [comment]
Thanks for reporting. This is finally fixed in master @ be134a8620de318d7930e633065327f5d33fcbaa
