### ISSUE TITLE
NullReferenceException on MonoCecilHelper.IsOrInheritedFrom method

### ISSUE THREAD

**Issue by IJEMIN** [Unity-Technologies/ProjectAuditor#142]
**Describe the bug**

NullReferenceException invoked when try to analyze code issues.

**To Reproduce**
1. Open Project Auditor Window
2. Select Code Module in Modules field from window.
3. Press Analyze
4. Code analyze failed. There is no entry in Code view.
And error in console view

Object reference not set to an instance of an object Unity.ProjectAuditor.Editor.CodeAnalysis.MonoCecilHelper.IsOrInheritedFrom (Mono.Cecil.TypeReference typeReference, System.String typeName)

**Expected behavior**
Code compilation finished without error and user can see code analysis on Code view. 

**Information (please complete the following information):**
 - OS: MacOS Ventura
 - Unity 2021.3.9
 - Project Auditor version 0.8.4 preview

**Comment by IJEMIN** [comment]
Update: it only happens in latest main branch. Didn't happen in release/0.8.4-preview branch

**Comment by mtrive** [comment]
@IJEMIN thanks for reporting. I was able to reproduce the exception and we will have a fix shortly.

**Comment by mtrive** [comment]
This should be fixed now. Thanks again for the bug report.
