### ISSUE TITLE
[Feedback] Allocation marked as critical even if called only once

### ISSUE THREAD

**Issue by marina-joffrineau** [Unity-Technologies/ProjectAuditor#30]
I have a static list that is set once and then ever again. Like this :

if (s_forbiddenSubareaList == null)
{
	s_forbiddenSubareaList = SubArea.GetAllSubArea().FindAll(s => s.m_mountAutoTripAllowed == false);
}

This code is included in a method that is called very often so the auditor is flagging it as a critical memory leak but in reality it's going to be called only once in the game lifetime.

**Comment by Appleguysnake** [comment]
I have the same issue, I get array allocation warnings even for fixed-length arrays that are only allocated in the field declaration

**Comment by mtrive** [comment]
I am afraid this is a limitation we are not going to solve anytime soon without some kind of runtime data analysis. Closing for now.

Thanks for reporting.
