### ISSUE TITLE
[Bug] Muted issue not staying muted

### ISSUE THREAD

**Issue by marina-joffrineau** [Unity-Technologies/ProjectAuditor#31]
Sometime muted issues come back on next analyse. I'm not sure of a 100% repro but for example it can happen if you mute an issue, edit some code and then come back to the auditor.

**Comment by mtrive** [comment]
Looks like the _mute_ preferences has been broken for a while. Basically, muted issues would not survive domain-reload. `0.8.2-preview` fixes the issue, however, just be aware that more fixes are likely coming in this area (for example, muting multiple issues does not work as expected).

Thanks for reporting, Marina.
