### ISSUE TITLE
[Bug] "View documentation" in Package Manager throws warning window that there is no documentation

### ISSUE THREAD

**Issue by patrickdevarney** [Unity-Technologies/ProjectAuditor#42]
Unity 2019.4.12f1, install via git url in Package Manager. **Package Manager > select Project Auditor > View documentation** throws a pop up that there is not offline documentation.

In other packages, this appears to link to online documentation. Should this link to this repo's docs page?

**Comment by mtrive** [comment]
Hi Patrick,
I installed `https://github.com/Unity-Technologies/ProjectAuditor.git#0.6.0-preview` and the doc opens with no warning.

what url did you use?

**Comment by patrickdevarney** [comment]
I am using `https://github.com/Unity-Technologies/ProjectAuditor.git`
Tested again today. Clicking view documentation now adds a .md file to my /Downloads folder and attempts to open in Edge. I think something is fishy with my Edge setup since it closes instantly.

**Comment by mtrive** [comment]
Closing this issue for the time being. Will reopen if we manage to repro.
