### ISSUE TITLE
[Bug] "Analysis in progress..." can show indefinitely

### ISSUE THREAD

**Issue by unitystevem** [Unity-Technologies/ProjectAuditor#47]
Steps to reproduce:

1. Select Assets/Editor/ProjectAuditorConfig and tick the "Log Timings Info" checkbox. Ensure the Console window is visible
2. Open Project Auditor, and click Analyze
3. After clicking the button, do not interact with the computer: don't move the mouse or touch the keyboard
4. Note how when the Project Auditor logs into the console that it has completed, the window still shows the yellow "Analysis in progress..." text. It will continue to do so until you reach step 5.
5. Mouse the mouse. The Project Auditor window will immediately refresh and stop showing the "Analysis in Progress..." text.

Expected results: Project Auditor window should refresh as soon as analysis is complete, so that it doesn't appear to be analyzing for much longer than it actually is.

**Comment by mtrive** [comment]
It should be fixed in 17732f14616ccbb2b24dba70419253f75737dc28
