### ISSUE TITLE
[Bug] player.log parsing for shader variant view throe if shader name has commas in it.

### ISSUE THREAD

**Issue by xdegtyarev** [Unity-Technologies/ProjectAuditor#51]
For the shader with the following name (it has commas in the name):
![image](https://user-images.githubusercontent.com/1286084/122293535-67e16200-cef7-11eb-9da2-ddc1fa70e80e.png)
When drag'n'dropping Player.log I'm getting the following exception in the console:
![image (1)](https://user-images.githubusercontent.com/1286084/122293529-66b03500-cef7-11eb-9204-ccf9f1b901be.png)

**Comment by mtrive** [comment]
This should be fixed by https://github.com/Unity-Technologies/ProjectAuditor/commit/7e10fdda4712063daaa8be528556e34448ebb52d

Thanks for the bug report!
