### ISSUE TITLE
[Bug] Overflow Exception on Analysis

### ISSUE THREAD

**Issue by Tymski** [Unity-Technologies/ProjectAuditor#52]
I tried to analyze a sizable project, it's been 7 hours already I have no idea if it's gonna finish analyzing. Task manager shows very little disk/processor usage for the Unity process...
![image](https://user-images.githubusercontent.com/8183632/123581245-cc47cf80-d7db-11eb-8fa4-0965e468df24.png)

**Comment by mtrive** [comment]
My guess is that something went wrong. Any error in the Console?

**Comment by Tymski** [comment]
No errors in the console

**Comment by Tymski** [comment]
I tried it again and there is an Overflow Exception:
![image](https://user-images.githubusercontent.com/8183632/124113109-59548800-da6b-11eb-9bf5-e5d12c32adb4.png)

**Comment by mtrive** [comment]
That should be fixed in _master_. Would you be able to check on your project?

**Comment by Tymski** [comment]
Yes, tried it again and it is now completed without the OverflowException.
