### ISSUE TITLE
Changing code breaks existing analysis

### ISSUE THREAD

**Issue by UnityAnthony** [Unity-Technologies/ProjectAuditor#54]
In 2020.3.7 if you run analysis then change the code, the system will update assemblies and the Project Auditor's content will be gone.

**Comment by mtrive** [comment]
Is everything gone, or just the Call Tree ?

**Comment by mtrive** [comment]
If you are referring to the "critical" issues, this is fixed in master @ be134a8620de318d7930e633065327f5d33fcbaa
