### ISSUE TITLE
nuget.mono-cecil: Package [nuget.mono-cecil@0.1.6-preview] cannot be found

### ISSUE THREAD

**Issue by ivan-hernandez-scopely** [Unity-Technologies/ProjectAuditor#62]
Yesterday we had to remove project-auditor because our docker builds started failing with:

```
Package com.unity.project-auditor@0.6.4-preview has invalid dependencies:
    nuget.mono-cecil: Package [nuget.mono-cecil@0.1.6-preview] cannot be found
```

Has nuget.mono-cecil 0.1.6-preview been removed?

**Comment by mtrive** [comment]
thanks for reporting this.

This is now fixed in `master` (latest) and `0.6.5-preview` (stable).
