### ISSUE TITLE
[Feature] Can build reports include the file path the build was created in?

### ISSUE THREAD

**Issue by unitystevem** [Unity-Technologies/ProjectAuditor#64]
During a Project Review, a customer asked whether the Build Report view could include the full path and (where appropriate) executable name for the folder that was selected to contain the build. I don't recall seeing that in the original Build Report Inspector so I don't know how easy this would be - although I'm pretty sure the build path ends up getting logged in the console window, so I guess it would show up in the Editor.log, so... Maybe?

Adding issue here as a reminder to investigate the possibility when there's time.

**Comment by mtrive** [comment]
they do now.
