### ISSUE TITLE
Couldn't delete Packages/com.unity.project-auditor/Editor/Icons.meta because it's in an immutable folder.

### ISSUE THREAD

**Issue by RomBinDaHouse** [Unity-Technologies/ProjectAuditor#65]
A meta data file (.meta) exists but its asset 'Packages/com.unity.project-auditor/Editor/Icons' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

**Comment by mtrive** [comment]
This is fixed in `master` now and will appear in the next release.

Thanks for reporting it!
