### ISSUE TITLE
Add editor preference to prevent PA from auto-opening after every build

### ISSUE THREAD

**Issue by nickfourtimes** [Unity-Technologies/ProjectAuditor#67]
It's handy to have the Project Auditor window pop up right after a build, but once PA is in your project it would be nice to disable the automatic behaviour when you're not making a build for auditing.

**Comment by mtrive** [comment]
https://github.com/Unity-Technologies/ProjectAuditor/commit/524bf6b48ed95346ad5d14739285cf42391f5255 changed the behavior so that Project Auditor will show its (updated) window only if it's already opened. Perhaps this is good enough and we don't need an option? Let me know what you think.

**Comment by nickfourtimes** [comment]
Oh yeah, just verified that in-editor. Works for me! The issue was less about having a toggle and more about keeping the window from popping up for folks who aren't running audits. I'll mark this issue closed, thanks.
