### ISSUE TITLE
Assembly not showing

### ISSUE THREAD

**Issue by archer-tate** [Unity-Technologies/ProjectAuditor#86]
**Describe the bug**
After running analyze, I don't see Assembly-CSharp in the list of assemblies which means I don't don't see an analysis on my code. What I do see are all the assemblies for the various packages that I have installed.

I created an assembly for my code and re-ran the analysis. The assembly that I created also does not show up in the list.

**To Reproduce**
1. Click analyze
2. Only assemblies for my packages are shown

**Expected behavior**
I can see an analysis on my code as well as the packages I have installed.

**Screenshots**
NDA

**Information (please complete the following information):**
 - Windows
 - Unity 2020.3.16f1
 - Latest project auditor version installed today via git url

**Comment by mtrive** [comment]
Hi @archer-tate,
thanks for the report. I am now trying to reproduce this issue on my side.

- Do you have any C# file under Assets, that you expect to be compiled into Assembly-CSharp ?
- When you say "Only assemblies for my packages are shown", do you mean in the Assemblies view?

Thanks,
Marco

**Comment by archer-tate** [comment]
Hi,

1. Yes I have many C# files under Assets which should be compiled into Assembly-CSharp.
2. In Assemblies view and Filters I only saw the assemblies for packages. Since creating this issue, I was able to create an assembly definition in the assets folder which was recognized by Project Auditor, but only in certain cases. I created 5 assembly definitions in various folders with Assets. 2 of them were detected by Project Auditor the rest were not.

**Comment by archer-tate** [comment]
Ok, good news. Your previous message lead to to figure out what was going on. I changed platforms from UWP to Windows standalone which cleared up all of the compilation errors. Now I can see assembly-csharp. Thanks!

**Comment by mtrive** [comment]
FYI - I found that Assemblies with dependencies that failed to compile, where not reported in the Assemblies view.
Let's say you have AssemblyA and AssemblyB, where AssemblyA depends on AssemblyB. If AssemblyB fails to compile, AssemblyA would not show up (because it's not compiled). This should be fixed now.
